import { useState } from "react";
import SignalCard from "../components/SignalCard";
import { mockSignals } from "../data/mockData";

export default function SignalsPage() {
  const [filterAction, setFilterAction] = useState<string>("ALL");
  const [filterPair, setFilterPair] = useState<string>("ALL");

  const filtered = mockSignals.filter((s) => {
    if (filterAction !== "ALL" && s.action !== filterAction) return false;
    if (filterPair !== "ALL" && s.pair !== filterPair) return false;
    return true;
  });

  return (
    <div className="relative min-h-screen pt-28 pb-20 px-6">
      <div
        className="orb w-80 h-80 top-20 right-0"
        style={{ background: "rgba(214,177,90,0.06)" }}
      />

      <div className="max-w-7xl mx-auto">
        <div className="mb-8">
          <div className="text-gold text-sm tracking-widest uppercase mb-2">
            AI-Powered
          </div>
          <h1 className="font-display text-4xl font-bold text-white uppercase tracking-tight">
            Trade Signals
          </h1>
          <p className="text-[#A7B0BC] mt-2">
            Real-time signals generated by Luxia's quantitative AI engine.
          </p>
        </div>

        {/* Filters */}
        <div className="flex flex-wrap items-center gap-3 mb-8">
          <div className="flex items-center gap-2">
            <span className="text-[#7E8896] text-xs uppercase tracking-wider">
              Action:
            </span>
            {["ALL", "BUY", "SELL", "HOLD"].map((a) => (
              <button
                type="button"
                key={a}
                onClick={() => setFilterAction(a)}
                className={`px-4 py-1.5 rounded-full text-xs font-bold tracking-wider uppercase transition-all ${
                  filterAction === a
                    ? a === "BUY"
                      ? "badge-buy"
                      : a === "SELL"
                        ? "badge-sell"
                        : a === "HOLD"
                          ? "badge-hold"
                          : "text-gold bg-gold/10 border border-gold/30"
                    : "glass text-[#A7B0BC] hover:text-white"
                }`}
              >
                {a}
              </button>
            ))}
          </div>
          <div className="flex items-center gap-2">
            <span className="text-[#7E8896] text-xs uppercase tracking-wider">
              Pair:
            </span>
            {["ALL", "BTC/USD", "ETH/USD", "SOL/USD"].map((p) => (
              <button
                type="button"
                key={p}
                onClick={() => setFilterPair(p)}
                className={`px-4 py-1.5 rounded-full text-xs font-semibold transition-all ${
                  filterPair === p
                    ? "text-gold bg-gold/10 border border-gold/30"
                    : "glass text-[#A7B0BC] hover:text-white"
                }`}
              >
                {p}
              </button>
            ))}
          </div>
        </div>

        {/* Grid */}
        {filtered.length === 0 ? (
          <div className="glass-card rounded-3xl p-12 text-center">
            <div className="text-4xl mb-3">&#8960;</div>
            <p className="text-[#7E8896]">No signals match your filters.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
            {filtered.map((s) => (
              <SignalCard key={s.id} signal={s} />
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
