/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface backendInterface {
    saveUsers(data: string): Promise<void>;
    getUsers(): Promise<string>;
    saveTrackedTrades(uid: string, data: string): Promise<void>;
    getTrackedTrades(uid: string): Promise<string>;
    saveAILearning(data: string): Promise<void>;
    getAILearning(): Promise<string>;
    saveCoinProfiles(data: string): Promise<void>;
    getCoinProfiles(): Promise<string>;
    saveAISkillLog(data: string): Promise<void>;
    getAISkillLog(): Promise<string>;
    saveAIParamHistory(data: string): Promise<void>;
    getAIParamHistory(): Promise<string>;
    saveAIRewriteLog(data: string): Promise<void>;
    getAIRewriteLog(): Promise<string>;
    recordGlobalOutcome(outcome: string): Promise<void>;
    getGlobalStats(): Promise<string>;
    getBingXSymbols(): Promise<string>;
    getCoinGeckoPage(page: bigint): Promise<string>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}

    async saveUsers(data: string): Promise<void> {
        try { await (this.actor as any).saveUsers(data); } catch (e) { if (this.processError) this.processError(e); else throw e; }
    }
    async getUsers(): Promise<string> {
        try { return await (this.actor as any).getUsers(); } catch (e) { if (this.processError) this.processError(e); else throw e; return ""; }
    }
    async saveTrackedTrades(uid: string, data: string): Promise<void> {
        try { await (this.actor as any).saveTrackedTrades(uid, data); } catch (e) { if (this.processError) this.processError(e); else throw e; }
    }
    async getTrackedTrades(uid: string): Promise<string> {
        try { return await (this.actor as any).getTrackedTrades(uid); } catch (e) { if (this.processError) this.processError(e); else throw e; return ""; }
    }
    async saveAILearning(data: string): Promise<void> {
        try { await (this.actor as any).saveAILearning(data); } catch (e) { if (this.processError) this.processError(e); else throw e; }
    }
    async getAILearning(): Promise<string> {
        try { return await (this.actor as any).getAILearning(); } catch (e) { if (this.processError) this.processError(e); else throw e; return ""; }
    }
    async saveCoinProfiles(data: string): Promise<void> {
        try { await (this.actor as any).saveCoinProfiles(data); } catch (e) { if (this.processError) this.processError(e); else throw e; }
    }
    async getCoinProfiles(): Promise<string> {
        try { return await (this.actor as any).getCoinProfiles(); } catch (e) { if (this.processError) this.processError(e); else throw e; return ""; }
    }
    async saveAISkillLog(data: string): Promise<void> {
        try { await (this.actor as any).saveAISkillLog(data); } catch (e) { if (this.processError) this.processError(e); else throw e; }
    }
    async getAISkillLog(): Promise<string> {
        try { return await (this.actor as any).getAISkillLog(); } catch (e) { if (this.processError) this.processError(e); else throw e; return ""; }
    }
    async saveAIParamHistory(data: string): Promise<void> {
        try { await (this.actor as any).saveAIParamHistory(data); } catch (e) { if (this.processError) this.processError(e); else throw e; }
    }
    async getAIParamHistory(): Promise<string> {
        try { return await (this.actor as any).getAIParamHistory(); } catch (e) { if (this.processError) this.processError(e); else throw e; return ""; }
    }
    async saveAIRewriteLog(data: string): Promise<void> {
        try { await (this.actor as any).saveAIRewriteLog(data); } catch (e) { if (this.processError) this.processError(e); else throw e; }
    }
    async getAIRewriteLog(): Promise<string> {
        try { return await (this.actor as any).getAIRewriteLog(); } catch (e) { if (this.processError) this.processError(e); else throw e; return ""; }
    }
    async recordGlobalOutcome(outcome: string): Promise<void> {
        try { await (this.actor as any).recordGlobalOutcome(outcome); } catch (e) { if (this.processError) this.processError(e); else throw e; }
    }
    async getGlobalStats(): Promise<string> {
        try { return await (this.actor as any).getGlobalStats(); } catch (e) { if (this.processError) this.processError(e); else throw e; return ""; }
    }
    async getBingXSymbols(): Promise<string> {
        try { return await (this.actor as any).getBingXSymbols(); } catch (e) { if (this.processError) this.processError(e); else throw e; return ""; }
    }
    async getCoinGeckoPage(page: bigint): Promise<string> {
        try { return await (this.actor as any).getCoinGeckoPage(page); } catch (e) { if (this.processError) this.processError(e); else throw e; return ""; }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
